### ISSUE TITLE
Check that the multiplicative group is closed under multipliacation 

### ISSUE THREAD

**Issue by nicolas3355** [bmabsout/Fibulus#1]
for all p1, p2 in G, (p3 = p1 * p2) should be in G. In other words, p3 should not be a hole.

A hole is defined by a pair (a, b) such that a and b is in Fp and Fib(a, b) does not have an inverse.

`inverse :: (Fractional a, Eq a) => Fib a -> Maybe (Fib a)
inverse (Fib a b)
  | a == 0 && b /= 0 = Just $ Fib (1/(-b)) (1/b)
  | a /=0 && b^2 /= a*(a + b) = Just $
      Fib ((a + b)/ (a^2 + a*b -b^2)) (-b/(a^2 + a*b - b^2))
  | otherwise = Nothing`

**Comment by bmabsout** [comment]
Closed it is padawan
